version: '3.8'

services:
  web:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
      - sqlite_data:/app/data
    env_file:
      - ../.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  sqlite_data:
