version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data
    environment:
      - DATABASE_TYPE=sqlite
      - API_KEY=your_secret_api_key
      - SQLITE_URL=sqlite:///./data/sql_app.db

volumes:
  sqlite_data:
